import SocialIcon from './SocialIcon';
import BookLink from './BookLink';
import ExtensionLink from './ExtensionLink';
import { extensions } from '../data/extensions';
import { trackEvent } from '../lib/analytics';
import '../styles/connect.css';

const channels = [
  { id: 'instagram', title: 'Instagram', mark: '◎', description: 'Comics, art, and behind-the-scenes nonsense.', label: 'Follow on Instagram', href: 'https://www.instagram.com/stoplosscomics/', character: 'luna' },
  { id: 'reddit', title: 'Reddit', mark: 'r/', description: 'Comics in the wild. Discussions and chaos with the community.', label: 'Find us on Reddit', href: 'https://www.reddit.com/r/stoplosscomics/', character: 'max' },
  { id: 'x', title: 'X', subtitle: 'The creator', mark: '𝕏', description: 'Plentiful Lee’s personal account. Thoughts, work in progress, and whatever’s on my mind.', label: 'Follow @plentifullee', href: 'https://x.com/plentifullee', character: 'chad' },
  { id: 'email', title: 'Email', mark: '✉', description: 'Questions, collaborations, licensing, press, or just want to say hi?', label: 'Send us an email', href: 'mailto:stoplosscomics@gmail.com', character: 'satoshi' },
];
export default function ConnectPage() {
  return <main id="main-content" tabIndex="-1" className="connect-page">
    <section className="connect-hero section-container" aria-labelledby="connect-title">
      <div><p className="eyebrow">The comics are just the beginning</p><h1 id="connect-title">Stay in<br />the <span>chaos.</span></h1><p>Comics, books, art and questionable financial decisions. Here’s everywhere you can find StopLoss Comics.</p></div>
      <div className="connect-hero-art"><img src="/images/connect-hero-1200.webp" srcSet="/images/connect-hero-600.webp 600w, /images/connect-hero-1200.webp 1200w" sizes="(max-width: 650px) calc(100vw - 32px), 58vw" width="1672" height="941" alt="Chad and Satoshi connecting an oversized plug and socket" fetchPriority="high" /><span className="connect-art-note">Good connections.<br />Questionable decisions.</span></div>
    </section>
    <div className="universe-strip connect-ribbon"><div className="section-container"><span>GOOD COMICS</span><i aria-hidden="true">✦</i><span>BAD INFLUENCES</span><i aria-hidden="true">✦</i><span>GREAT COMPANY</span></div></div>
    <section className="section-container connect-socials" aria-labelledby="connect-social-title"><h2 id="connect-social-title" className="connect-heading">Follow the chaos</h2><p className="connect-subtitle">Different platforms, different vibes. Same comics.</p><div className="connect-grid">{channels.map(channel => <article key={channel.id} className={`connect-card connect-${channel.id}`}><div className="connect-card-title"><span className="connect-mark" aria-hidden="true"><SocialIcon name={channel.id} /></span><h3>{channel.title}{channel.subtitle && <small>{channel.subtitle}</small>}</h3></div><p>{channel.description}</p><a className="connect-channel-link" href={channel.href} target={channel.id === 'email' ? undefined : '_blank'} rel={channel.id === 'email' ? undefined : 'noopener noreferrer'} onClick={() => trackEvent('connect_click', { destination: channel.id, location: 'connect_page' })}>{channel.label} <span aria-hidden="true">↗</span>{channel.id !== 'email' && <span className="sr-only"> (opens in a new tab)</span>}</a>{channel.id === 'email' && <small className="connect-email-address">stoplosscomics@gmail.com</small>}</article>)}</div></section>
    <section className="section-container connect-promos" aria-label="Explore StopLoss Comics"><div className="connect-reading"><img src="/images/connect-reading-960.webp" srcSet="/images/connect-reading-480.webp 480w, /images/connect-reading-960.webp 960w" sizes="(max-width: 650px) calc(100vw - 72px), 45vw" width="1672" height="941" alt="Max, Luna, Chad and Satoshi relaxing together with their books" loading="lazy" decoding="async" /><div><h2 className="connect-heading">Read the <span>comics</span></h2><p>A growing archive of comics about crypto, startups, AI and modern life.</p><a href="/#comics" className="comic-button" onClick={() => trackEvent('comic_archive_click', { location: 'connect_page' })}>Start reading →</a></div></div><div className="connect-book"><a className="connect-book-cover" href="https://books2read.com/stoplosscomicsvolume1" aria-label="Get StopLoss Comics Volume 1" onClick={() => trackEvent('book_cta_click', { location: 'connect_cover' })}><img src="/images/volume-1-384.webp" srcSet="/images/volume-1-384.webp 384w, /images/volume-1-512.webp 512w" sizes="(max-width: 650px) 160px, 210px" width="1024" height="1536" alt="StopLoss Comics Volume 1 by Plentiful Lee" loading="lazy" /></a><div><p className="eyebrow">All the chaos. In one book.</p><h2>StopLoss Comics: Volume 1</h2><p>Degens, Dreams &amp; Disasters from the Crypto Frontlines.</p><BookLink location="connect_page">Get the book</BookLink></div><ul><li>70 original episodes</li><li>60 new comics</li><li>Bonus content</li><li>Your favorite degens</li></ul></div></section>
    <section className="section-container connect-elsewhere" aria-labelledby="connect-elsewhere-title"><h2 id="connect-elsewhere-title" className="connect-heading">Elsewhere in the chaos</h2><p className="connect-subtitle">More StopLoss Comics, onchain and beyond.</p><div>{extensions.map(extension => <article key={extension.id}><span aria-hidden="true">{extension.id === 'opensea' ? '✦' : '↗'}</span><div><h3>{extension.title}</h3><p>{extension.description}</p><ExtensionLink extension={extension} location="connect_page" className="connect-channel-link">{extension.cta}</ExtensionLink></div></article>)}</div></section>
    <section className="connect-finish final-cta"><div className="section-container"><div><h2>Still here?</h2><p>Good. Now go read something.</p></div><a className="comic-button" href="/#comics">Read the comics →</a></div></section>
  </main>;
}
